apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jatdilok-odds/argocd-leaning.git'
    targetRevision: main
    path: argocd/configuration/tools
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
