apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: su-smart-applicaitonset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: dev
  template:
    metadata:
      name: new-su-smart-dev
      namespace: argocd
    spec:
      project: new-su-smart
      source:    
        repoURL: 'https://gitlab.odd.limited/nssp/new-su-smart-infra.git'
        targetRevision: HEAD
        path: apps/dev
      destination: 
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: {}
      # metadata:
      # will generate applications with different names for example (dev-color-app, test-color-app, etc..)
      # name: '{{Namespace}}-color-app'
    # spec:
    #   # applications will be in default project for argocd
    #   project: 'new-su-smart-{{Namespace}}'
    #   source:
    #     repoURL: 'https://gitlab.odd.limited/nssp/new-su-smart-infra.git'
    #     targetRevision: HEAD
    #     path: apps/dev
    #   destination:
    #     # default cluster as destination, you can define multiple clusters in ArgoCD UI
    #     server: https://kubernetes.default.svc
    #     # will deploy to different namespaces as different destinations 
    #     namespace: '{{Namespace}}'
    #   syncPolicy:
    #     syncOptions:
    #     - CreateNamespace=true
    #     automated: {}
