apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-example-applicaitonset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: dev
  template:
    metadata:
      name: app-example-dev
      namespace: argocd
    spec:
      project: app-example
      source:    
        repoURL: 'https://gitlab.com/learning-devops101/argocd.git'
        targetRevision: HEAD
        path: apps/dev
      destination: 
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: {}