apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-example-applicaitonset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        manifestfile: dev
      - namespace: uat
        manifestfile: uat
      - namespace: prod
        manifestfile: prod
  template:
    metadata:
      name: 'app-example-{{namespace}}'
      namespace: argocd
    spec:
      project: 'app-example'
      source:    
        repoURL: 'https://gitlab.com/learning-devops101/argocd.git'
        targetRevision: HEAD
        path: 'apps/{{manifestfile}}'
      destination: 
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: {}