elasticsearch:
  clusterName: "elasticsearch"
  nodeGroup: "master"
  replicas: 2
  minimumMasterNodes: 1
  secret:
    enabled: true
    password: "ElasticsearchPassword" # generated randomly if not defined
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  imageTag: "8.5.1"
  imagePullPolicy: "IfNotPresent"
  esJavaOpts: "" # example: "-Xmx1g -Xms1g"
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  networkHost: "0.0.0.0"
  # volumeClaimTemplate:
  #   accessModes: ["ReadWriteOnce"]
  #   resources:
  #     requests:
  #       storage: 5Gi