apiVersion: v2
name: kube-monitoring-stack
description: Helm install with kube-monitoring-stack dependency
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"