kube-prometheus-stack:
  global:
    rbac:
      create: true

  crds:
    enabled: true

  # prometheus:
  #   prometheusSpec:
  #     storageSpec:
  #       volumeClaimTemplate:
  #         spec:
  #           storageClassName: gluster
  #           accessModes: ["ReadWriteOnce"]
  #           resources:
  #             requests:
  #               storage: 5Gi
  #         selector: {}
  ## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  grafana:
    enabled: true
    namespaceOverride: ""
    # size: 500Mi
    # Uncomment and set to the name of an existing PVC if you want to use an existing one
    # existingClaim: my-existing-pvc
    ingress:
      enabled: true ## If true, Grafana Ingress will be created
      ## IngressClassName for Grafana Ingress.
      ## Should be provided if Ingress is enable.
      ingressClassName: nginx
      ## Annotations for Grafana Ingress
      annotations:
        kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      ## Labels to be added to the Ingress
      labels: {}
      ## Hostnames.
      ## Must be provided if Ingress is enable.
      hosts:
        - grafana.local.com
      ## Path for grafana ingress
      path: /
      ## TLS configuration for grafana Ingress
      ## Secret must be manually created in the namespace
      tls: []
      # - secretName: grafana-general-tls
      #   hosts:
      #   - grafana.example.com