# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx-ingress:
  controller:
    replicaCount: 2
    service:
      type: LoadBalancer
  defaultBackend:
    enabled: true
