# nginx-ingress:
#   controller:
#     replicaCount: 2
#     service:
#       type: NodePort
#   defaultBackend:
#     enabled: true

ingress-nginx:
  controller:
    replicaCount: 2
    service:
      type: NodePort

# controller:
#   replicaCount: 2
#   service:
#     type: NodePort