apiVersion: v1
kind: Secret
metadata:
  name: public-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/jatdilok-odds/argocd-leaning.git
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/jatdilok-odds/argocd-private.git
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/jatdilok-odds/argocd-private.git
  password: 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
  username: jatdilok-odds